title: Lunar's AltspaceVR Scripts
description: Since the release of the new sdk, and a more or less difinitive depreciation date of the old one, this will just serve as an archive.
url: https://lunartiger.github.io/AltspaceVR